name = "image-uploader" # todo
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

kv_namespaces = [
  { binding = "IMAGES", id = "" },
]

[vars]
WORKERS_RS_VERSION = "0.0.11"

[build]
command = "cargo install -q worker-build --version 0.0.7 && worker-build --release"

